media:
  - label: Images
    name: images
    input: images
    output: /images
    categories: [ image ]
  - label: Files
    name: files
    input: files
    output: /files
content:
  - name: posts
    label: Posts
    path: blog
    type: collection
    view:
      fields: [ images, title, date, body ]
    fields:
      - name: title
        label: Title
        type: string
      - name: author
        label: Author
        type: reference
        options:
          collection: authors
          search: [ fields.name ]
          label: "{fields.name}"
          value: "{github_id}"
      - name: tag
        label: Tag
        type: select
        options:
          multiple: true
          values: [Technology, Programming, AI, Web, Data, ML, Cybersecurity, Cloud, DevOps, Software]
      - name: images
        label: Images
        type: image
        options:
          multiple: true
      - name: attachments
        label: Attachments
        type: file
        options:
          multiple: true
          media: files
          extensions: [ pdf, zip ]
      - name: body
        label: Body
        type: text
        options:
          autoresize: false
          minlength: 3
          maxlength: 9
          rows: 24
  - name: authors
    label: Authors
    type: collection
    path: authors
    view:
      fields: [ photo, name, email, github_id, uuid ]
    fields:
      - name: uuid
        type: uuid
        label: UUID
        options:
          editable: true
      - name: photo
        label: Photo
        type: image
        options:
          path: images/photos
      - name: name
        label: Full name
        type: string
      - name: email
        label: Email
        type: string
        pattern: ^(|[\w\.-]+@[\w\.-]+\.\w+)$
      - name: github_id
        label: GitHub ID
        type: select
        options:
          fetch:
            url: https://api.github.com/search/users
            method: GET
            params:
              q: "{input}"
            default: "hunvreus"
            results: items
            value: "{id}"
            label: "{login} ({type})"
            image: "https://github.com/{login}.png"
            minlength: 2
            headers:
              Authorization: Bearer ghp_xxxxxxxxx # Disabled the GitHub token
